majors = {
    "AAST": "Asian American Studies",
    "ACBU": "Accounting",
    "AFAM": "African and American Studies",
    "AMCS": "American Catholic Studies",
    "AMST": "American Studies",
    "ANTH": "Anthropology",
    "ARAB": "Arabic",
    "ARHI": "Art History",
    "BISC": "Biological Sciences",
    "BLBU": "Business Law",
    "CBBU": "Core Business",
    "CEED": "Center of Ethics Education",
    "CHEM": "Chemistry and Biochemistry",
    "CISC": "Computer and Information Sciences",
    "CLAS": "Classical Languages and Civilization",
    "CMBU": "Business Communications",
    "COLI": "Comparative Literature",
    "COMC": "Communication and Media Studies",
    "COMM": "Communications",
    "DANC": "Dance",
    "DISA": "Disability Studies",
    "DTEM": "Digital Technologies and Media",
    "ECON": "Economics",
    "ENGL": "English",
    "ENST": "Environmental Studies",
    "ENVS": "Environmental Science",
    "FASH": "Fashion Studies",
    "FITV": "Film and Television",
    "FNBU": "Finance",
    "FREN": "French",
    "GERM": "German",
    "GREK": "Greek",
    "HEBW": "Hebrew",
    "HIST": "History",
    "HPCB": "Honors Program - Gabelli",
    "HPLC": "Honors Program - FCLC",
    "HPRH": "Honors Program - FCRH",
    "HUST": "Humanitarian Studies",
    "INST": "International Studies",
    "INSY": "Information Systems",
    "ITAL": "Italian",
    "JPAN": "Japanese",
    "JOUR": "Journalism",
    "LALS": "Latin American and Latino Studies",
    "LATN": "Latin",
    "LING": "Linguistics",
    "LPBU": "Leading People and Organizations",
    "MAND": "Mandarin Chinese",
    "MATH": "Mathematics",
    "MKBU": "Marketing",
    "MLAL": "Modern Languages",
    "MUSC": "Music",
    "MVST": "Medieval Studies",
    "NSCI": "Natural Science",
    "NMDD": "New Media and Digital Design",
    "OPBU": "Operations",
    "PHIL": "Philosophy",
    "PHYS": "Physics",
    "PJST": "Peace and Justice Studies",
    "POSC": "Political Science",
    "PSYC": "Psychology",
    "RUSS": "Russian",
    "SABU": "Strategy",
    "SOCI": "Sociology",
    "SPAN": "Spanish",
    "THEA": "Theatre",
    "THEO": "Theology",
    "URST": "Urban Studies",
    "VART": "Visual Arts",
    "WGSS": "Gender Studies",
}

buildings = {
    "ALPHA HOUSE": "Alpha House",
    "CO": "Collins Hall",
    "CO AUD": "Collins Hall Auditorium",
    "DE": "Dealy Hall",
    "DU": "Duane Library",
    "FA": "Faber Hall",
    "FMH": "Faculty Memorial Hall",
    "FR": "Freeman Hall",
    "HU": "Hughes Hall",
    "JMH": "John Mulcahy Hall",
    "KE": "Keating Hall",
    "LH": "Larkin Hall",
    "LO": "Loyola Hall",
    "QCR": "Queens Court",
    "2CA": "",
    "3SA": "",
}
