# Generated by Django 5.1.2 on 2024-10-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exam_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_start_time',
            field=models.DateTimeField(),
        ),
    ]
